### ISSUE TITLE
Install fail on vue 3

### ISSUE THREAD

**Issue by fxcjahid** [hilongjw/vue-progressbar#101]
Hello, 
I have uses vue 3 app.
But, after configuration  VueProgressBar it couldn't install.
Show the following issues on the console log.
`vue-progressbar.js:1 Uncaught TypeError: o is not a constructor
    at Object.install (vue-progressbar.js:1:5953)
    at Object.use (runtime-core.esm-bundler.js:4327:28)
    at main.js?t=1663055188118:69:5
`
[https://prnt.sc/v-7XWAJuwgYS](https://prnt.sc/v-7XWAJuwgYS)

My code is :
```vuejs
import { createApp } from "vue";
import App from "./App.vue";
import VueProgressBar from 'vue-progressbar';

const app = createApp(App);
app.use(VueProgressBar, {
    color: 'rgb(143, 255, 199)',
    failedColor: 'red',
    height: '2px'
});

app.mount("#app");
```

Please, Help me to solve this

**Comment by webwizard0822** [comment]
@fxcjahid 
Currently, I have same issue in my Vue 3 project. 
`Uncaught TypeError: o is not a constructor
    at Object.install (vue-progressbar.js:1:5953)
    at Object.use (runtime-core.esm-bundler.js:4327:28)
    at main.ts:49:5`

In ReadMe, it's compatible with Vue 1.x or 2.x.
No way to use this package in Vue 3?

What package works with Vue 3?

Thanks in advance

**Comment by joseprest** [comment]
Uncaught TypeError: o is not a constructor
    at Object.install (vue-progressbar.js:1:5953)
    at Object.use (runtime-core.esm-bundler.js:4327:28)
    at main.ts:49:5
    
I have same problem in Vue 3 project ( use VITE )


- No way to use this package in Vue 3?
- What package is compatible with Vue 3?

**Comment by TT-EL** [comment]
I encounted a new error like this:

``` shell
couldn't find declare file of module "vue-progressbar". 
"../node_modules/vue-progressbarr/dist/vue-progressbar.js" implied has "any" type. 
Try to use "npm -i --save-dev @type/vue-progressbar"(if exist), 
or add a new declaration contains "declare module 'vue-progressbar';"
```

**Comment by FotieMConstant** [comment]
Hey, just had the same issue and noticed someone has refined the component to have a vue3 compatibility.

here: https://github.com/aacassandra/vue3-progressbar

Hope that helps anyone who comes across this as well in the future!
