### ISSUE TITLE
external-helpers

### ISSUE THREAD

**Issue by paveldrvn** [hilongjw/vue-progressbar#80]
packege.json :

`{
  "name": "m",
  "version": "1.0.0",
  "description": "d",
  "author": "d",
  "private": true,
  "scripts": {
    "webpack": "webpack --config webpack.config.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
  "dependencies": {
    "vue": "^2.5.2",
    "vue-progressbar": "^0.7.5",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "webpack-bundle-analyzer": "^2.9.0",
    "node-notifier": "^5.1.2",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "portfinder": "^1.0.13",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`
main.js 
`import VueProgressBar from 'vue-progressbar'
`
webpack.config.js:
`const webpack = require('webpack');
const path = require('path');

module.exports = {
	entry: [ './main.js'],
	watch: true,
	module: {
		rules: [
			{
				test: /\.js$/,
				loader: 'babel-loader',
			},
			{
				test: /\.css$/,
				exclude: /node_modules/,
				use: [
					{
						loader: 'style-loader',
					},
					{
						loader: 'css-loader',
						options: {
							importLoaders: 1,
						}
					},
					{
						loader: 'postcss-loader'
					}
				]
			}
		],
	},
	resolve: {
		extensions: ['.tsx', '.ts', '.js'],
	},
	plugins: [
	],
	output: {
		path: path.join(__dirname, 'dist'),
		filename: 'server.js',
	},
};`

when I'm trying to compile main.js with webpack I have this error :
`Webpack is watching the files…

Hash: 1fc9a1610a1ee1093ba1
Version: webpack 3.12.0
Time: 729ms
    Asset     Size  Chunks             Chunk Names
server.js  5.32 kB       0  [emitted]  main
   [0] multi ./main.js 28 bytes {0} [built]
   [1] ./main.js 45 bytes {0} [built]
    + 1 hidden module

ERROR in ./node_modules/vue-progressbar/dist/vue-progressbar.js
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "C:\\OpenServer\\domains\\localhost\\302\\d_visualize\\admin\\view\\javascript\\d_visualize\\webpack\\node_modules\\vue-progressbar\\.babelrc" at 0, attempted to resolve relative to "C:\\OpenServer\\domains\\localhost\\302\\d_visualize\\admin\\view\\javascript\\d_visualize\\webpack\\node_modules\\vue-progressbar"
    at C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\OpenServer\domains\localhost\302\d_visualize\admin\view\javascript\d_visualize\webpack\node_modules\babel-loader\lib\index.js:173:20)
 @ ./main.js 1:0-45
 @ multi ./main.js`

**Comment by vratojr** [comment]
I have the same problem
